Add `silent-tests' and `logged-tests' variables
By default, tests and suites log their results in the *Messages*
buffer. If `logged-tests' is nil, results are not logged;
if `silent-tests' is t, results are not even echoed.

Exception: if `silent-tests' is t and a test or suite is called
interactively, the result is echoed, but not logged.